import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${nunito.className} antialiased`}>
        <Toaster position="top-right" richColors closeButton />
        <main className="flex h-full min-h-screen flex-col">{children}</main>
      </body>
    </html>
  );
}
